# Generated by Django 3.1.5 on 2021-02-25 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('tenure_period', models.CharField(max_length=100)),
                ('rate_of_interest', models.CharField(max_length=50)),
                ('interest_amount', models.FloatField()),
                ('amount_to_be_paid', models.FloatField()),
                ('final_rate', models.FloatField()),
                ('due_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.IntegerField()),
                ('pan', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField(default=datetime.datetime(2021, 2, 25, 12, 26, 38, 12141, tzinfo=utc))),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
